Controllers/AdminsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BooksMagazine.Data;
using BooksMagazine.Models;

namespace BooksMagazine.Controllers
{
    public class AdminsController : Controller
    {
        private readonly BooksMagazineContext _context;

        public AdminsController(BooksMagazineContext context)
        {
            _context = context;
        }

        // GET: Admins/AddAdmin
        public IActionResult AddAdmin(string token)
        {
            var admin = new Admin()
            {
                Token = token
            };
            return View(admin);
        }

        // POST: Admins/AddAdmin
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddAdmin(Admin admin)
        {
            
            _context.Add(admin);
            await _context.SaveChangesAsync();
            return Redirect("/Admins/Login");
        }
        // GET: Admins/Login
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(Admin admin)
        {
            if (admin == null)
            {
                return NotFound();
            }
            var item = await _context.Admin.FirstOrDefaultAsync(a => a.UserName == admin.UserName);
            
            if(item !=null)
            {
                if (admin.Password == item.Password && admin.Token == item.Token)
                {
                    Helpers.Constants.Admin = item;
                }
            }
            return Redirect("/home");
        }
        // GET: /Admins/GetToken
        public IActionResult GetToken()
        {
            return View();
        }
        [HttpPost] 
        [ValidateAntiForgeryToken]
        public IActionResult GetToken(TokenParamater tokenParamater)
        {
            var str = GenerateToken(tokenParamater);
            return Redirect($"/Admins/AddAdmin/?token={str}");
        }
        public IActionResult LogOut()
        {
            Helpers.Constants.Admin = null;
            return Redirect("/Home");
        }
        string str0; string str1;  
        private string GenerateToken(TokenParamater tokenParamater)
        {
            foreach (var item in tokenParamater.UserName)
            {
                var r = new Random();
                str0 += r.Next(9) + item + r.Next(9) + item + r.Next(9) + item;
            }
            foreach (var item in tokenParamater.Birthaday)
            {
                var r = new Random();
                for (int i = 0; i < 3; i++)
                {
                    str1 += r.Next(9);
                }
                str1 += item;
            }

            return str0 + str1;
        }
    }
}

Controllers/BooksController.cs
using BooksMagazine.Data;
using BooksMagazine.Models;
using BooksMagazine.ViewModels.BookViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace BooksMagazine.Controllers
{
    public class BooksController : Controller
    {
        private readonly BooksMagazineContext _context;

        [System.Obsolete]
        public BooksController(BooksMagazineContext context, IHostingEnvironment hostingEnvironment)
        {
            _context = context;
            Helpers.Methods.hostingEnvironment = hostingEnvironment;
        }

        // GET: Books
        public async Task<IActionResult> Index()
        {
            return View(await _context.Book.ToListAsync());
        }
        // GET: Books/Details/5
        public async Task<IActionResult> Type(string type)
        {
            if (type == string.Empty)
            {
                return NotFound();
            }

            var book = await _context.Book.Where(p => p.Type == type).ToListAsync();
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Book
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: Books/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateBookViewModel book)
        {
            if (book.History == null)
            {
                if (book.History == null)
                {
                    if (book.BookFile != null && book.CoverImageFile != null)
                    {
                        Helpers.Methods.CreateItem(book.BookFile, true);
                        Helpers.Methods.CreateItem(book.CoverImageFile);
                    }
                    else
                        return NotFound();

                    var item = CreateNewBook(book);

                    _context.Add(item);
                    await _context.SaveChangesAsync();
                    return Redirect("/Home");
                }
            }
            return Redirect("/Home");
        }

        // GET: Books/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Book.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Type,Title,AuthorName,CoverImage,Description,ReleaseDate")] Book book)
        {
            if (id != book.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(book);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(book.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }

        // GET: Books/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Book
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var book = await _context.Book.FindAsync(id);
            _context.Book.Remove(book);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookExists(int id)
        {
            return _context.Book.Any(e => e.Id == id);
        }

        private Book CreateNewBook(CreateBookViewModel book)
        {
            return new Book()
            {
                Id = book.Id != default ? book.Id : book.Id,
                AuthorName = book.AuthorName,
                Description = book.Description,
                ReleaseDate = book.ReleaseDate,
                Title = book.Title,
                Type = book.Type,
                CoverImage = book.CoverImageFile != null ? book.CoverImageFile.FileName : book.CoverImage,
                Link = book.BookFile != null ? book.BookFile.FileName : book.Link,
            };
        }
    }
}

Controllers/ContactUsController.cs
using BooksMagazine.Data;
using BooksMagazine.Models;
using BooksMagazine.ViewModels.ContactUsViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace BooksMagazine.Controllers
{
    public class ContactUsController : Controller
    {
        private readonly BooksMagazineContext _context;

        public ContactUsController(BooksMagazineContext context)
        {
            _context = context;
        }

        // GET: ContactUs
        public async Task<IActionResult> Index()
        {
            return View(await _context.ContactUs.ToListAsync());
        }

        // GET: ContactUs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contactUs = await _context.ContactUs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (contactUs == null)
            {
                return NotFound();
            }

            return View(contactUs);
        }

        // GET: ContactUs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ContactUs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateContactUsViewModel contactUs)
        {
            if (contactUs.Topic == null)
            {
                var item = CreateNewContactUs(contactUs);

                _context.Add(item);
                await _context.SaveChangesAsync();
                return Redirect("/Home");
            }
            return Redirect("/Home");
        }

        // GET: ContactUs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contactUs = await _context.ContactUs.FindAsync(id);
            if (contactUs == null)
            {
                return NotFound();
            }
            return View(contactUs);
        }

        // POST: ContactUs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Emaail,PhoneNumber,Subject,Description")] ContactUs contactUs)
        {
            if (id != contactUs.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(contactUs);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContactUsExists(contactUs.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(contactUs);
        }

        // GET: ContactUs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contactUs = await _context.ContactUs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (contactUs == null)
            {
                return NotFound();
            }

            return View(contactUs);
        }

        // POST: ContactUs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var contactUs = await _context.ContactUs.FindAsync(id);
            _context.ContactUs.Remove(contactUs);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ContactUsExists(int id)
        {
            return _context.ContactUs.Any(e => e.Id == id);
        }
        private ContactUs CreateNewContactUs(CreateContactUsViewModel contactUs)
        {
            return new ContactUs()
            {
                Id = contactUs.Id != default ? contactUs.Id : contactUs.Id,
                Email = contactUs.Email,
                Description = contactUs.Description,
                Name = contactUs.Name,
                PhoneNumber = contactUs.PhoneNumber,
                Subject = contactUs.Subject
            };
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Books Magazine</title>
    <!-- Bootstrap core CSS -->
    <link href="~/lib/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Fontawesome CSS -->
    <link href="~/css/all.css" rel="stylesheet">
    <!-- Owl Carousel CSS -->
    <link href="~/css/owl.carousel.min.css" rel="stylesheet">
    <!-- Owl Carousel CSS -->
    <link href="~/css/jquery.fancybox.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="~/css/style.css" rel="stylesheet">

</head>
<body>
    <div class="wrapper-main">
        <!-- Navigation Bar -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-light top-nav">
            <div class="container">

                <!--logo -->
                <a class="navbar-brand"  asp-controller="Home" asp-action="Index">
                    <img src="/images/ISAMM_Logo.png" alt="logo" />
                </a>

                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="fas fa-bars"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <!--Home Button-->
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <!--About Button-->
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="About" asp-action="Index">About</a>
                        </li>
                        <!--Portfolio_Lists Button-->
                        <li class="nav-item dropdown">
                            <a class="nav-link" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Check Books <i class="fas fa-sort-down"></i></a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
                                <a class="dropdown-item" asp-controller="Books" asp-action="Index">All Categories</a>
                                @if (BooksMagazine.Helpers.Constants.BooksTypeName.Count > 0)
                                {
                                    foreach (var item in BooksMagazine.Helpers.Constants.BooksTypeName.ToList())
                                    {
                                        <a class="dropdown-item" asp-controller="Books" asp-action="Type" asp-route-Type="@item">@Html.DisplayFor(i => item)</a>
                                    }
                                }
                            </div>
                        </li>
                        <!--Blog_Lists Button-->
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Books" asp-action="Create">Create a book</a>
                        </li>
                        <!--Contact Button-->
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="ContactUs" asp-action="Create">Contact</a>
                        </li>

                        @if (BooksMagazine.Helpers.Constants.Admin != null)
                        {
                            <!--Add Admin Button-->
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Admins" asp-action="GetToken">Add Admin</a>
                            </li>
                            <!--Contact Log Out-->
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Admins" asp-action="GetToken">Log Out</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>

        <!-- body rendered -->
        <div>
            <main role="main">
                @RenderBody()
            </main>
        </div>
        


        <!-- Contact_Us Section: above footer -->
        <div class="touch-line">
            <div class="container">
                <div class="row">
                    <div class="col-md-8">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, expedita, saepe, vero rerum deleniti beatae veniam harum neque nemo praesentium cum alias asperiores commodi.</p>
                    </div>
                    <div class="col-md-4">
                        <a class="btn btn-lg btn-secondary btn-block" href="#"> Contact Us </a>
                    </div>
                </div>
            </div>
        </div>
        <!--footer Section-->
        <footer class="footer">
            <div class="container bottom_border">
                <div class="row">
                    <!--About Us-->
                    <div class="col-lg-3 col-md-6 col-sm-6 col">
                        <h5 class="headin5_amrc col_white_amrc pt2">About Us</h5>

                        <p class="mb10">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</p>
                        <ul class="footer-social">
                            <li><a class="facebook hb-xs-margin" href="#"><span class="hb hb-xs spin hb-facebook"><i class="fab fa-facebook-f"></i></span></a></li>
                            <li><a class="twitter hb-xs-margin" href="#"><span class="hb hb-xs spin hb-twitter"><i class="fab fa-twitter"></i></span></a></li>
                            <li><a class="instagram hb-xs-margin" href="#"><span class="hb hb-xs spin hb-instagram"><i class="fab fa-instagram"></i></span></a></li>
                            <li><a class="googleplus hb-xs-margin" href="#"><span class="hb hb-xs spin hb-google-plus"><i class="fab fa-google-plus-g"></i></span></a></li>
                            <li><a class="dribbble hb-xs-margin" href="#"><span class="hb hb-xs spin hb-dribbble"><i class="fab fa-dribbble"></i></span></a></li>
                        </ul>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6">
                        <h5 class="headin5_amrc col_white_amrc pt2">Quick links</h5>

                        <!--Follow us-->
                        <ul class="footer_ul_amrc">
                            <li><a href="#"><i class="fas fa-long-arrow-alt-right"></i>Default Version</a></li>
                            <li><a href="#"><i class="fas fa-long-arrow-alt-right"></i>Boxed Version</a></li>
                            <li><a href="#"><i class="fas fa-long-arrow-alt-right"></i>Our Team </a></li>
                            <li><a href="#"><i class="fas fa-long-arrow-alt-right"></i>About Us</a></li>
                            <li><a href="#"><i class="fas fa-long-arrow-alt-right"></i>Our Services</a></li>
                            <li><a href="#"><i class="fas fa-long-arrow-alt-right"></i>Get In Touch</a></li>
                        </ul>
                        <!--footer_ul_amrc ends here-->
                    </div>
                    <!--Follow us-->
                    <div class="col-lg-3 col-md-6 col-sm-6 col">
                        <h5 class="headin5_amrc col_white_amrc pt2">Follow us</h5>
                        <!--headin5_amrc ends here-->
                        <ul class="footer_ul2_amrc">
                            <li>
                                <a href="#"><i class="fab fa-twitter fleft padding-right"></i> </a>
                                <p>Lorem Ipsum is simply dummy...<a href="#">https://www.lipsum.com/</a></p>
                            </li>
                            <li>
                                <a href="#"><i class="fab fa-twitter fleft padding-right"></i> </a>
                                <p>Lorem Ipsum is simply dummy...<a href="#">https://www.lipsum.com/</a></p>
                            </li>
                            <li>
                                <a href="#"><i class="fab fa-twitter fleft padding-right"></i> </a>
                                <p>Lorem Ipsum is simply dummy...<a href="#">https://www.lipsum.com/</a></p>
                            </li>
                        </ul>
                        <!--footer_ul2_amrc ends here-->
                    </div>
                    <!--News Letter-->
                    <div class="col-lg-3 col-md-6 col-sm-6 ">
                        <div class="news-box">
                            <h5 class="headin5_amrc col_white_amrc pt2">Newsletter</h5>
                            <p>Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...</p>
                            <form action="#">
                                <div class="input-group">
                                    <input class="form-control" placeholder="Search for..." type="text">
                                    <span class="input-group-btn">
                                        <button class="btn btn-secondary" type="button">Go!</button>
                                    </span>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            <div class="container">
                <p class="copyright text-center">
                    &copy; @DateTime.Now.Year -  Books Magazine - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </p>
            </div>
        </footer>
    </div>

    <!-- Bootstrap core JavaScript -->
    <div>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/lib/vendor/jquery/jquery.min.js"></script>
        <script src="~/lib/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/imagesloaded.pkgd.min.js"></script>
        <script src="~/js/isotope.pkgd.min.js"></script>
        <script src="~/js/filter.js"></script>
        <script src="~/js/jquery.appear.js"></script>
        <script src="~/js/owl.carousel.min.js"></script>
        <script src="~/js/jquery.fancybox.min.js"></script>
    </div>
    @RenderSection("Scripts", required: false)
</body>
</html>